language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t sashamihalache/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sashamihalache/react-test npm test

after_success:
  - docker build -t sashamihalache/multi-client:latest ./client
  - docker build -t sashamihalache/multi-nginx:latest ./nginx
  - docker build -t sashamihalache/multi-server:latest ./server
  - docker build -t sashamihalache/multi-worker:latest ./worker
  # Login to docker-cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to Docker Hub
  - docker push sashamihalache/multi-client:latest
  - docker push sashamihalache/multi-nginx:latest
  - docker push sashamihalache/multi-server:latest
  - docker push sashamihalache/multi-worker:latest

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-multi
  env: DockerMulti-env
  bucket_name: elasticbeanstalk-us-east-1-714959141112
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY 
