version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8080:80'
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    depends_on:
      - postgres
    volumes:
      - /app/node_modules # ignore node_modules from app in linux img
      - ./server:/app # watch over all other files and rebuild image (saves time instead of rebuilding) - whatever happens in /server, gets reflected in /app, except /node_modules
    environment:
      - REDIS_HOST=redis # this is the above-defined service
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules # don't override this
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    environment:
      - REDIS_HOST=redis # this is the above-defined service
      - REDIS_PORT=6379
    volumes:
      - /app/node_modules
      - ./worker:/app # mapp everything except above line